---
- name: Create fonts directory
  become: true
  file:
    path: "{{ fonts_path }}"
    mode: '0755'
    state: directory

- name: Copy powerlevel10k recommanded fonts
  become: true
  copy:
    src: "fonts/{{ item }}"
    dest: "{{ fonts_path }}/{{ item }}"
    mode: '0644'
  loop:
    - MesloLGS NF Bold Italic.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Regular.ttf